### ISSUE TITLE
Error: Cannot find module 'react'

### ISSUE THREAD

**Issue by archenroot** [Hyperline/hyperline#127]
```
zangetsu@localhost ~/.hyper_plugins/local/hyperline $ hyper
Gtk-Message: Failed to load module "canberra-gtk-module"
{ Error: Cannot find module 'react'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/Hyper/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:73:18)
    at __webpack_require__ (/home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:20:30)
    at Object.<anonymous> (/home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:1334:64)
    at __webpack_require__ (/home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:20:30)
    at /home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:66:18 code: 'MODULE_NOT_FOUND' }
[Notification] Plugin error!: Plugin "hyperline" failed to load (Cannot find module 'react')
running in prod mode
electron will open file:///opt/Hyper/resources/app.asar/index.html
[Notification] Plugin error!: Plugin "hyperline" failed to load (Cannot find module 'react')
Checking for notification messages
ignoring auto updates during dev
No matching notification messages

```

**Comment by archenroot** [comment]
After I added react latest version available into "dependencies" block I got another error:
```
zangetsu@localhost ~/.hyper_plugins/local/hyperline $ hyper
Gtk-Message: Failed to load module "canberra-gtk-module"
{ Error: Cannot find module 'hyper/component'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/Hyper/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:79:18)
    at __webpack_require__ (/home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:20:30)
    at Object.<anonymous> (/home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:151:74)
    at __webpack_require__ (/home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:20:30)
    at Object.<anonymous> (/home/zangetsu/.hyper_plugins/local/hyperline/dist/hyperline.js:1336:78) code: 'MODULE_NOT_FOUND' }
[Notification] Plugin error!: Plugin "hyperline" failed to load (Cannot find module 'hyper/component')
running in prod mode
electron will open file:///opt/Hyper/resources/app.asar/index.html
[Notification] Plugin error!: Plugin "hyperline" failed to load (Cannot find module 'hyper/component')
Checking for notification messages
ignoring auto updates during dev
No matching notification messages

```

**Comment by archenroot** [comment]
I am on branch hyper-2.0.4,maybe I should install latest dev branch.

**Comment by gabemeola** [comment]
Looks like it isn't a dependency in package.json https://github.com/Hyperline/hyperline/blob/48381dd6f906599b8ad083d55bb04622127b963c/package.json#L28

**Comment by mloberg** [comment]
Using version "0.6.1" fixed Hyperline for me. Use `hyperline#0.6.1` instead of `hyperline` in your plugins list.

**Comment by Mohamed3on** [comment]
Same issue here

**Comment by systemovich** [comment]
@mloberg's suggestion works, but then the prompt is missing.

**Comment by ButchAnton** [comment]
I was experiencing the same problem.  After forcing hyperline version 0.6.1, things started working again.  If it doesn't immediately work, make sure you delete the .hyper_plugins directory and do a full reload of the plugins from within hyper.

**Comment by kidchenko** [comment]
+1

**Comment by tbsvttr** [comment]
Same issue here!

**Comment by xeijin** [comment]
Still broken for me too, adding #0.6.1 resolves for now...

**Comment by bhavikbhavsar** [comment]
facing same issue!

**Comment by yipsang** [comment]
The issue still exists, how come it's closed?
