### ISSUE TITLE
hyper 2.1 breaks it cannot find React.proptypes

### ISSUE THREAD

**Issue by gulakov** [Hyperline/hyperline#129]
bundle.js:1 TypeError: Cannot read property 'string' of undefined
    at hyperlineFactory (/home/alex/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:223:33)
    at decorateHyper (/home/alex/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:124:52)

**Comment by erik-helmers** [comment]
Hello ! I have the same problem here... On Ubuntu 16.04 LTS, after updating Hyper to 2.1.1... But it was working fine before the update

**Comment by ymatuhin** [comment]
Same on Mac OS High Sierra
