### ISSUE TITLE
Error: Cannot find module 'prop-types'

### ISSUE THREAD

**Issue by mssngr** [Hyperline/hyperline#134]
Does not load and throws an Error in dev tools:
```
bundle.js:1 Error: Cannot find module 'prop-types'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Function.c._load (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:8001)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gbriel/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:128:18)
    at __webpack_require__ (/Users/gbriel/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:20:30)
    at Object.<anonymous> (/Users/gbriel/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:1339:69)
    at __webpack_require__ (/Users/gbriel/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:20:30)
```

**Comment by db369** [comment]
I have the exact same error on Hyper 1.4.8.  I tried the latest pre-release of Hyper as well, but had the same error.

**Comment by gabemeola** [comment]
yup I have to manual add prop-types to `.hyper_plugins/` dir

**Comment by usrbowe** [comment]
@gabemeola with installing `prop-types` it started working, but it continued complaining about other missing packages, like `react` and the style is kinda broken.

**Comment by NickTikhonov** [comment]
Hey all - this was caused by a new version that switched the plugin over to using `prop-types`. Did a rollback to the old version, hopefully everything should be fine. Will look into a better fix soon!

**Comment by sanfilippopablo** [comment]
@NickTikhonov I keep getting this error while installing the plugin, how can I roll back the version?

**Comment by jacec** [comment]
I had the same issue so rolled back (as suggested by @mloberg in issue [Error: Cannot find module 'react'](https://github.com/Hyperline/hyperline/issues/127) "Using version "0.6.1" fixed Hyperline for me. Use hyperline#0.6.1 instead of hyperline in your plugins list.")

**Comment by sanfilippopablo** [comment]
@jacec Thanks!

**Comment by julien-HAM** [comment]
Add prop-types to the plugins

`...`
